#pragma once

#include <global_Compiler.h>
#include <global_Features.h>

#define HAVE_LOCALTIME_R 1
#define HAVE_STRINGS_H 1
#define HAVE_PTHREAD_NP_H 0

#define HAVE_STACK_BOUNDS_FOR_NEW_THREAD 1

#define PLATFORM(WTF_FEATURE) (defined WTF_PLATFORM_##WTF_FEATURE && WTF_PLATFORM_##WTF_FEATURE)
#define CPU(WTF_FEATURE) (defined WTF_CPU_##WTF_FEATURE && WTF_CPU_##WTF_FEATURE)
#define HAVE(WTF_FEATURE) (defined HAVE_##WTF_FEATURE && HAVE_##WTF_FEATURE)
#define OS(WTF_FEATURE) (defined WTF_OS_##WTF_FEATURE && WTF_OS_##WTF_FEATURE)
#define USE(WTF_FEATURE) (defined USE_##WTF_FEATURE && USE_##WTF_FEATURE)
#define ENABLE(WTF_FEATURE) (defined ENABLE_##WTF_FEATURE && ENABLE_##WTF_FEATURE)

#define WTF_PLATFORM_JSCJS 1

#define WTF_OS_UNIX 1
#define USE_PTHREADS 1
#define USE_SYSTEM_MALLOC 1
#define WTF_DEFAULT_EVENT_LOOP 1
#define USE_GENERIC_EVENT_LOOP 1
#define GIGACAGE_ENABLED 0
#define WTF_CPU_NEEDS_ALIGNED_ACCESS 1

#define LLIntOffsetsExtractor CLoop
#define ENABLE_COMPUTED_GOTO 1
#define ENABLE_COMPUTED_GOTO_OPCODES 1

#if defined(WTF_CPU_ADDRESS64) && WTF_CPU_ADDRESS64
#define USE_JSVALUE64 1
#else
#define USE_JSVALUE32_64 1
#endif