// Automatically generated from /mnt/d/Dev/webkit-04062019/Source/JavaScriptCore/runtime/ObjectConstructor.cpp using /mnt/d/Dev/webkit-04062019/Source/JavaScriptCore/create_hash_table. DO NOT EDIT!

#include "JSCBuiltins.h"
#include "Lookup.h"

namespace JSC {

static const struct CompactHashIndex objectConstructorTableIndex[67] = {
    { 1, 66 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 16, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 13, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 20, -1 },
    { -1, -1 },
    { -1, -1 },
    { 11, -1 },
    { -1, -1 },
    { -1, -1 },
    { 8, -1 },
    { 19, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 0, -1 },
    { 15, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 5, 65 },
    { -1, -1 },
    { 10, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 9, -1 },
    { -1, -1 },
    { 17, -1 },
    { -1, -1 },
    { 12, -1 },
    { -1, -1 },
    { 3, -1 },
    { -1, -1 },
    { 14, -1 },
    { 7, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 2, 64 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 4, -1 },
    { 6, -1 },
    { 18, -1 },
};

static const struct HashTableValue objectConstructorTableValues[21] = {
   { "getPrototypeOf", static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), ObjectGetPrototypeOfIntrinsic, { (intptr_t)static_cast<RawNativeFunction>(objectConstructorGetPrototypeOf), (intptr_t)(1) } },
   { "setPrototypeOf", static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { (intptr_t)static_cast<RawNativeFunction>(objectConstructorSetPrototypeOf), (intptr_t)(2) } },
   { "getOwnPropertyDescriptor", static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { (intptr_t)static_cast<RawNativeFunction>(objectConstructorGetOwnPropertyDescriptor), (intptr_t)(2) } },
   { "getOwnPropertyDescriptors", static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { (intptr_t)static_cast<RawNativeFunction>(objectConstructorGetOwnPropertyDescriptors), (intptr_t)(1) } },
   { "getOwnPropertyNames", static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { (intptr_t)static_cast<RawNativeFunction>(objectConstructorGetOwnPropertyNames), (intptr_t)(1) } },
   { "getOwnPropertySymbols", static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { (intptr_t)static_cast<RawNativeFunction>(objectConstructorGetOwnPropertySymbols), (intptr_t)(1) } },
   { "keys", static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), ObjectKeysIntrinsic, { (intptr_t)static_cast<RawNativeFunction>(objectConstructorKeys), (intptr_t)(1) } },
   { "defineProperty", static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { (intptr_t)static_cast<RawNativeFunction>(objectConstructorDefineProperty), (intptr_t)(3) } },
   { "defineProperties", static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { (intptr_t)static_cast<RawNativeFunction>(objectConstructorDefineProperties), (intptr_t)(2) } },
   { "create", static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), ObjectCreateIntrinsic, { (intptr_t)static_cast<RawNativeFunction>(objectConstructorCreate), (intptr_t)(2) } },
   { "seal", static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { (intptr_t)static_cast<RawNativeFunction>(objectConstructorSeal), (intptr_t)(1) } },
   { "freeze", static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { (intptr_t)static_cast<RawNativeFunction>(objectConstructorFreeze), (intptr_t)(1) } },
   { "preventExtensions", static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { (intptr_t)static_cast<RawNativeFunction>(objectConstructorPreventExtensions), (intptr_t)(1) } },
   { "isSealed", static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { (intptr_t)static_cast<RawNativeFunction>(objectConstructorIsSealed), (intptr_t)(1) } },
   { "isFrozen", static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { (intptr_t)static_cast<RawNativeFunction>(objectConstructorIsFrozen), (intptr_t)(1) } },
   { "isExtensible", static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { (intptr_t)static_cast<RawNativeFunction>(objectConstructorIsExtensible), (intptr_t)(1) } },
   { "is", static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), ObjectIsIntrinsic, { (intptr_t)static_cast<RawNativeFunction>(objectConstructorIs), (intptr_t)(2) } },
   { "assign", static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { (intptr_t)static_cast<RawNativeFunction>(objectConstructorAssign), (intptr_t)(2) } },
   { "values", static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { (intptr_t)static_cast<RawNativeFunction>(objectConstructorValues), (intptr_t)(1) } },
   { "entries", ((static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function)) & ~PropertyAttribute::Function) | PropertyAttribute::Builtin, NoIntrinsic, { (intptr_t)static_cast<BuiltinGenerator>(objectConstructorEntriesCodeGenerator), (intptr_t)1 } },
   { "fromEntries", ((static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function)) & ~PropertyAttribute::Function) | PropertyAttribute::Builtin, NoIntrinsic, { (intptr_t)static_cast<BuiltinGenerator>(objectConstructorFromEntriesCodeGenerator), (intptr_t)1 } },
};

static const struct HashTable objectConstructorTable =
    { 21, 63, false, nullptr, objectConstructorTableValues, objectConstructorTableIndex };

} // namespace JSC
