// Automatically generated from /mnt/d/Dev/webkit-04062019/Source/JavaScriptCore/runtime/RegExpConstructor.cpp using /mnt/d/Dev/webkit-04062019/Source/JavaScriptCore/create_hash_table. DO NOT EDIT!

#include "Lookup.h"

namespace JSC {

static const struct CompactHashIndex regExpConstructorTableIndex[65] = {
    { -1, -1 },
    { 8, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 12, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 10, -1 },
    { -1, -1 },
    { -1, -1 },
    { 7, -1 },
    { 2, -1 },
    { 9, -1 },
    { 16, -1 },
    { -1, -1 },
    { -1, -1 },
    { 19, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 3, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 4, -1 },
    { -1, -1 },
    { -1, -1 },
    { 5, 64 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 17, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 14, -1 },
    { -1, -1 },
    { 11, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 6, -1 },
    { -1, -1 },
    { 15, -1 },
    { -1, -1 },
    { 0, -1 },
    { -1, -1 },
    { 18, -1 },
    { 20, -1 },
    { 13, -1 },
};

static const struct HashTableValue regExpConstructorTableValues[21] = {
   { "input", static_cast<unsigned>(PropertyAttribute::None), NoIntrinsic, { (intptr_t)static_cast<PropertySlot::GetValueFunc>(regExpConstructorInput), (intptr_t)static_cast<PutPropertySlot::PutValueFunc>(setRegExpConstructorInput) } },
   { "$_", static_cast<unsigned>(PropertyAttribute::DontEnum), NoIntrinsic, { (intptr_t)static_cast<PropertySlot::GetValueFunc>(regExpConstructorInput), (intptr_t)static_cast<PutPropertySlot::PutValueFunc>(setRegExpConstructorInput) } },
   { "multiline", static_cast<unsigned>(PropertyAttribute::None), NoIntrinsic, { (intptr_t)static_cast<PropertySlot::GetValueFunc>(regExpConstructorMultiline), (intptr_t)static_cast<PutPropertySlot::PutValueFunc>(setRegExpConstructorMultiline) } },
   { "$*", static_cast<unsigned>(PropertyAttribute::DontEnum), NoIntrinsic, { (intptr_t)static_cast<PropertySlot::GetValueFunc>(regExpConstructorMultiline), (intptr_t)static_cast<PutPropertySlot::PutValueFunc>(setRegExpConstructorMultiline) } },
   { "lastMatch", static_cast<unsigned>(PropertyAttribute::DontDelete|PropertyAttribute::ReadOnly), NoIntrinsic, { (intptr_t)static_cast<PropertySlot::GetValueFunc>(regExpConstructorLastMatch), (intptr_t)static_cast<PutPropertySlot::PutValueFunc>(0) } },
   { "$&", static_cast<unsigned>(PropertyAttribute::DontDelete|PropertyAttribute::ReadOnly|PropertyAttribute::DontEnum), NoIntrinsic, { (intptr_t)static_cast<PropertySlot::GetValueFunc>(regExpConstructorLastMatch), (intptr_t)static_cast<PutPropertySlot::PutValueFunc>(0) } },
   { "lastParen", static_cast<unsigned>(PropertyAttribute::DontDelete|PropertyAttribute::ReadOnly), NoIntrinsic, { (intptr_t)static_cast<PropertySlot::GetValueFunc>(regExpConstructorLastParen), (intptr_t)static_cast<PutPropertySlot::PutValueFunc>(0) } },
   { "$+", static_cast<unsigned>(PropertyAttribute::DontDelete|PropertyAttribute::ReadOnly|PropertyAttribute::DontEnum), NoIntrinsic, { (intptr_t)static_cast<PropertySlot::GetValueFunc>(regExpConstructorLastParen), (intptr_t)static_cast<PutPropertySlot::PutValueFunc>(0) } },
   { "leftContext", static_cast<unsigned>(PropertyAttribute::DontDelete|PropertyAttribute::ReadOnly), NoIntrinsic, { (intptr_t)static_cast<PropertySlot::GetValueFunc>(regExpConstructorLeftContext), (intptr_t)static_cast<PutPropertySlot::PutValueFunc>(0) } },
   { "$`", static_cast<unsigned>(PropertyAttribute::DontDelete|PropertyAttribute::ReadOnly|PropertyAttribute::DontEnum), NoIntrinsic, { (intptr_t)static_cast<PropertySlot::GetValueFunc>(regExpConstructorLeftContext), (intptr_t)static_cast<PutPropertySlot::PutValueFunc>(0) } },
   { "rightContext", static_cast<unsigned>(PropertyAttribute::DontDelete|PropertyAttribute::ReadOnly), NoIntrinsic, { (intptr_t)static_cast<PropertySlot::GetValueFunc>(regExpConstructorRightContext), (intptr_t)static_cast<PutPropertySlot::PutValueFunc>(0) } },
   { "$'", static_cast<unsigned>(PropertyAttribute::DontDelete|PropertyAttribute::ReadOnly|PropertyAttribute::DontEnum), NoIntrinsic, { (intptr_t)static_cast<PropertySlot::GetValueFunc>(regExpConstructorRightContext), (intptr_t)static_cast<PutPropertySlot::PutValueFunc>(0) } },
   { "$1", static_cast<unsigned>(PropertyAttribute::DontDelete|PropertyAttribute::ReadOnly), NoIntrinsic, { (intptr_t)static_cast<PropertySlot::GetValueFunc>(regExpConstructorDollar<1>), (intptr_t)static_cast<PutPropertySlot::PutValueFunc>(0) } },
   { "$2", static_cast<unsigned>(PropertyAttribute::DontDelete|PropertyAttribute::ReadOnly), NoIntrinsic, { (intptr_t)static_cast<PropertySlot::GetValueFunc>(regExpConstructorDollar<2>), (intptr_t)static_cast<PutPropertySlot::PutValueFunc>(0) } },
   { "$3", static_cast<unsigned>(PropertyAttribute::DontDelete|PropertyAttribute::ReadOnly), NoIntrinsic, { (intptr_t)static_cast<PropertySlot::GetValueFunc>(regExpConstructorDollar<3>), (intptr_t)static_cast<PutPropertySlot::PutValueFunc>(0) } },
   { "$4", static_cast<unsigned>(PropertyAttribute::DontDelete|PropertyAttribute::ReadOnly), NoIntrinsic, { (intptr_t)static_cast<PropertySlot::GetValueFunc>(regExpConstructorDollar<4>), (intptr_t)static_cast<PutPropertySlot::PutValueFunc>(0) } },
   { "$5", static_cast<unsigned>(PropertyAttribute::DontDelete|PropertyAttribute::ReadOnly), NoIntrinsic, { (intptr_t)static_cast<PropertySlot::GetValueFunc>(regExpConstructorDollar<5>), (intptr_t)static_cast<PutPropertySlot::PutValueFunc>(0) } },
   { "$6", static_cast<unsigned>(PropertyAttribute::DontDelete|PropertyAttribute::ReadOnly), NoIntrinsic, { (intptr_t)static_cast<PropertySlot::GetValueFunc>(regExpConstructorDollar<6>), (intptr_t)static_cast<PutPropertySlot::PutValueFunc>(0) } },
   { "$7", static_cast<unsigned>(PropertyAttribute::DontDelete|PropertyAttribute::ReadOnly), NoIntrinsic, { (intptr_t)static_cast<PropertySlot::GetValueFunc>(regExpConstructorDollar<7>), (intptr_t)static_cast<PutPropertySlot::PutValueFunc>(0) } },
   { "$8", static_cast<unsigned>(PropertyAttribute::DontDelete|PropertyAttribute::ReadOnly), NoIntrinsic, { (intptr_t)static_cast<PropertySlot::GetValueFunc>(regExpConstructorDollar<8>), (intptr_t)static_cast<PutPropertySlot::PutValueFunc>(0) } },
   { "$9", static_cast<unsigned>(PropertyAttribute::DontDelete|PropertyAttribute::ReadOnly), NoIntrinsic, { (intptr_t)static_cast<PropertySlot::GetValueFunc>(regExpConstructorDollar<9>), (intptr_t)static_cast<PutPropertySlot::PutValueFunc>(0) } },
};

static const struct HashTable regExpConstructorTable =
    { 21, 63, true, nullptr, regExpConstructorTableValues, regExpConstructorTableIndex };

} // namespace JSC
